### ISSUE TITLE
Unable to get connection

### ISSUE THREAD

**Issue by pastebin** [CatoAntonsen/MMM-SpotifyConnectUI#10]
I've tried to add this module, all works well, except for when it's time to use it.
I only get the black spotify-logo.

MMM-SpotifyConnectUI received a system notification: ALL_MODULES_STARTED

`<img src="modules/MMM-SpotifyConnectUI//images/Spotify_Icon_RGB_Black.png" class="spotifyMissingConnectionImage">
`
Can't seem to get it to connect.

**Comment by CatoAntonsen** [comment]
Do you see it as available in Spotify on mobile or computer?

**Comment by pastebin** [comment]
If i view it from my computer, it says the same thing. Also, when trying to run it with the following command: 
`./spotify-connect-web.sh --username 12345678 --password xyz123 --bitrate 320`

It says it cant find the spotify_appkey.key

Not sure if that's the issue here?

**Comment by CatoAntonsen** [comment]
Did you download the key-file as specified in my documentation?

"Now you need to register as developer at Spotify (free!) to be able to register and download a 'spotify_appkey.key'. This file should be placed in the ~/spotify-connect-web folder."

This is anyway not an issue with this module, but with the 3rd party application found here: https://github.com/Fornoth/spotify-connect-web.
