### ISSUE TITLE
Only getting information when selecting magic mirror as output.

### ISSUE THREAD

**Issue by DieterKoblenz** [CatoAntonsen/MMM-SpotifyConnectUI#9]
At the moment I am only getting track information when I select magicmirror as output. This is undesirable as I have a connect box standalone from the pi running my mirror.

Web interface from the spotify connect module shows the current track regardless.

**Comment by CatoAntonsen** [comment]
I'm only using a third party Spotify Connect software, so this is out of the scope for the module at the moment.
